version: "3.8"

services:
  db:
    container_name: db-mysql-template-node-dev
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_api_node_data_dev:/var/lib/mysql

volumes:
  mysql_api_node_data_dev:
